---
- name: Ensure ZSH is installed
  become: true
  apt:
    name: zsh
    state: present

- name: Set zsh as the default shell for the current user
  become: true
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh

- name: Install Oh My Zsh [1/2]
  block: 
    - name: [1/2]
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install.sh
        mode: 0755
        force: yes

    - name: [2/2]
      shell: /tmp/install.sh

- name: Install packer
  git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    clone: yes

- name: Install PowerLevel10K theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
    clone: yes

- name: Install autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes

- name: Install syntax highligher plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    clone: yes
