---
- name: Ensure ZSH is installed
  apt:
    name: zsh
    state: present
  become: true

- name: Set zsh as the default shell for the current user
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
