---
- name: Ensure ZSH is installed
  apt:
    name: zsh
    state: present
  become: true

- name: Set zsh as the default shell for the current user
  become: true
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
