---
- hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  # Not updating the package manager repo because it will be redundant, the script has already taked care of this

  roles:
    - shell
    - tools
    - dotfiles

  # The reason this is kept for last, because a new linux machine may need reboots when upgrading packages
  post_tasks:
    - name: upgrade packages to latest
      apt:
        name: "*"
        state: latest
