---
- hosts: localhost
  connection: local

  vars:
    user: "{{ lookup('env', 'USER') }}"

  # Not updating the package manager repo because it will be redundant, the script has already taked care of this

  roles:
    - shell
    - tools
    - dotfiles

  # The reason this is kept for last, because a new linux machine may need reboots when upgrading packages
  post_tasks:
    - name: upgrade packages to latest
      become: true
      block:
        - name: Update apt repo
          command: apt update
          
        - name: apt packages
          apt:
            upgrade: yes
            autoremove: yes
            autoclean: yes

        - name: snap packages
          command: snap refresh

    - name: Reboot the system
      become: true
      shell: reboot
