---
- hosts: localhost
  connection: local

  vars:
    user: "{{ ansible_env.USER }}"

  pre_tasks:
  - name: update package manager repo
    apt:
      update_cache: true
    become: true

  - name: upgrade packages to latest
    apt:
      name: "*"
      state: latest
    become: true

  roles:
    - shell
    #- tools
    #- dotfiles
