---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: update package manager repo
    apt:
      update_cache: true

  - name: upgrade packages to latest
    apt:
      name: "*"
      state: latest

  roles:
    - shell
    #- style
    #- tools
    #- dotfiles
