---
- name: Copy zshrc file
  become_user: "{{ user }}"
  copy:
    src: zshrc
    dest: "/home/{{ user }}/.zshrc"

- name: Copy zshenv file
  become_user: "{{ user }}"
  copy:
    src: zshenv
    dest: "/home/{{ user }}/.zshenv"

- name: Copy oh-my-zsh configs
  become_user: "{{ user }}"
  copy:
    src: oh-my-zsh
    dest: "/home/{{ user }}/.oh-my-zsh"

- name: Copy o10k.zsh file
  become_user: "{{ user }}"
  copy:
    src: p10k.zsh
    dest: "/home/{{ user }}/.p10k.zsh"

- name: Copy nvim config
  become_user: "{{ user }}"
  copy:
    src: nvim
    dest: "/home/{{ user }}/.config"

- name: Install Packer Packages
  become_user: "{{ user }}"
  block:
    - name: Run PackerSync
      command: "nohup nvim -c 'lua require(\"omar.packer\").sync()' &"
      async: 20
      poll: 20

    - name: Copy /nvim/after directory
      copy:
        src: after
        dest: "/home/{{ user }}/.config/nvim"
