---
- name: Copy zshrc file
  become_user: "{{ user }}"
  copy:
    src: zshrc
    dest: "/home/{{ user }}/.zshrc"

- name: Copy zshenv file
  become_user: "{{ user }}"
  copy:
    src: zshenv
    dest: "/home/{{ user }}/.zshenv"

- name: Copy oh-my-zsh configs
  become_user: "{{ user }}"
  copy:
    src: oh-my-zsh
    dest: "/home/{{ user }}/.oh-my-zsh"

- name: Copy o10k.zsh file
  become_user: "{{ user }}"
  copy:
    src: p10k.zsh
    dest: "/home/{{ user }}/.p10k.zsh"

- name: Copy nvim config
  become_user: "{{ user }}"
  copy:
    src: nvim
    dest: "/home/{{ user }}/.config"

- name: Run PackerSync
  shell: "nvim -c \"lua require('omar.packer').sync()\" &"
  async: 300
  poll: 0
  register: packer_install_process

- name: Halt for 10 seconds
  async_status:
    jid: "{{ packer_install_process.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 20
  delay: 1

- name: Kill nvim from the background
  shell: "kill -9 {{ packer_install_process.ansible_return_code.pid }}"
  when: job_result.failed

- name: Copy /nvim/after directory
  become_user: "{{ user }}"
  copy:
    src: nvim-after
    dest: "/home/{{ user }}/.config/nvim/after"
