---
- name: Copy zshrc file
  become_user: "{{ user }}"
  copy:
    src: zshrc
    dest: "/home/{{ user }}/.zshrc"

- name: Copy zshenv file
  become_user: "{{ user }}"
  copy:
    src: zshenv
    dest: "/home/{{ user }}/.zshenv"

- name: Copy oh-my-zsh configs
  become_user: "{{ user }}"
  copy:
    src: oh-my-zsh
    dest: "/home/{{ user }}/.oh-my-zsh"

- name: Copy o10k.zsh file
  become_user: "{{ user }}"
  copy:
    src: p10k.zsh
    dest: "/home/{{ user }}/.p10k.zsh"

- name: Copy nvim config
  become_user: "{{ user }}"
  copy:
    src: nvim
    dest: "/home/{{ user }}/.config/nvim"

- name: Run PackerSync
  become_user: "{{ user }}"
  shell: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"
