---
- name: Copy zshrc file
  become_user: "{{ user }}"
  copy:
    src: zshrc
    dest: "/home/{{ user }}/.zshrc"

- name: Copy zshenv file
  become_user: "{{ user }}"
  copy:
    src: zshenv
    dest: "/home/{{ user }}/.zshenv"

- name: Copy oh-my-zsh configs
  become_user: "{{ user }}"
  copy:
    src: oh-my-zsh
    dest: "/home/{{ user }}/.oh-my-zsh"

- name: Copy o10k.zsh file
  become_user: "{{ user }}"
  copy:
    src: p10k.zsh
    dest: "/home/{{ user }}/.p10k.zsh"

- name: Copy nvim config
  become_user: "{{ user }}"
  copy:
    src: nvim
    dest: "/home/{{ user }}/.config"

- name: Run PackerSync
  become_user: "{{ user }}"
  block:
    - name: Create script
      copy:
        content: |
          #!/bin/bash
          nvim -c "lua require('omar.packer').sync" &
          my_pid=$!
          sleep 10
          kill $my_pid
        dest: /tmp/run_packer.sh
        mode: 0755

    - name: Run script
      command: /tmp/run_packer.sh
      async: 0
      poll: 0
      ignore_errors: yes

- name: Copy /nvim/after directory
  become_user: "{{ user }}"
  copy:
    src: after
    dest: "/home/{{ user }}/.config/nvim"
