---
- name: Copy zshrc file
  copy:
    src: zshrc
    dest: "/home/{{ user }}/.zshrc"

- name: Copy zshenv file
  copy:
    src: zshenv
    dest: "/home/{{ user }}/.zshenv"

- name: Copy oh-my-zsh configs
  copy:
    src: oh-my-zsh
    dest: "/home/{{ user }}/.oh-my-zsh"

- name: Copy o10k.zsh file
  copy:
    src: p10k.zsh
    dest: "/home/{{ user }}/.p10k.zsh"

- name: Copy nvim config
  copy:
    src: nvim
    dest: "/home/{{ user }}/.config"

- name: Install Packer Packages
  block:
    - name: Run PackerSync
      command: "nohup nvim -c 'lua require(\"omar.packer\").sync()' &"
      async: 20
      poll: 20
      ignore_errors: true

    - name: Copy /nvim/after directory
      copy:
        src: after
        dest: "/home/{{ user }}/.config/nvim"

- name: Copy tmux configs
  block:
    - name: Clone tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        clone: yes

    - name: Copy tmux.conf file
      copy:
        src: tmux.conf
        dest: "/home/{{ user }}/.tmux.conf"

    - name: Install tmux packages
      shell: "~/.tmux/plugins/tpm/bin/install_plugins"
