---
- name: Install necessary apt packages
  become: true
  apt:
    name:
      - tmux
      - ripgrep
      - bat
      - clang
      
- name: Install necessary snap packages
  become: true
  community.general.snap:
    name:
      - lsd
      - nvim
      - node
    classic: true

- name: Install packer
  git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    clone: yes

- name: Install Rust [1/2]
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0755
    force: yes

- name: Install Rust [2/2]
  shell: /tmp/sh.rustup.rs -y
