---
- name: Install necessary apt packages
  apt:
    name:
      - tmux
      - ripgrep
      - bat
      - clang
      
- name: Install necessary snap packages
  community.general.snap:
    name:
      - nvim
      - node
    classic: true

- name: Install packer
  become_user: "{{ user }}"
  git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    clone: yes

- name: Install Rust [1/2]
  become_user: "{{ user }}"
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0755
    force: yes

- name: Source bashrc
  become_user: "{{ user }}"
  shell: source ~/.bashrc

- name: Install Rust [2/2]
  become_user: "{{ user }}"
  shell: /tmp/sh.rustup.rs -y

- name: Install lsd
  command: cargo install lsd
